image: atlassian/default-image:2

pipelines:
    branches: # Branch-specific pipelines definitions
        master:
            - step:
                name: Build and Test
                image: node:latest
                services: 
                  - mysql
                script:
                  - cd src
                  - npm install
                  - apt-get update && apt-get install -y default-mysql-client
                  - mysql -h 127.0.0.1 -u root -proot -e "CREATE DATABASE IF NOT EXISTS imobidb"
                  - mysql -h 127.0.0.1 -u root -proot -e "SHOW DATABASES"
                  - mysql -h 127.0.0.1 -u root -proot < ../database/script.sql
                  - npm test
                

    # default: Pipeline definition for branched that don't match a pipeline definition

    custom: # Pipeline that only runs manually
        production:
            - step:
                name: Building and Test the app
                image: node:latest
                script:
                    - cd src
                    - npm install
                    - apt-get update && apt-get install -y default-mysql-client
                    - mysql -h 127.0.0.1 -u root -proot -e "CREATE DATABASE IF NOT EXISTS imobidb"
                    - mysql -h 127.0.0.1 -u root -proot -e "SHOW DATABASES"
                    - mysql -h 127.0.0.1 -u root -proot < ../database/script.sql
                    - npm test
                services: 
                  - mysql
            - step:
                name: Deploying the app to EC2
                deployment: production
                script:
                    - cd src
                    - apt-get update
                    - apt-get install -y zip
                    - zip -r application1.zip .
                    - pipe: atlassian/aws-code-deploy:0.2.5
                      variables:
                          AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                          AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                          AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                          APPLICATION_NAME: $APPLICATION_NAME
                          S3_BUCKET: $S3_BUCKET
                          COMMAND: 'upload'
                          ZIP_FILE: 'application1.zip'
                          VERSION_LABEL: 'my-app-1.0.0'
                    - pipe: atlassian/aws-code-deploy:0.2.5
                      variables:
                        AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                        AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                        AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                        APPLICATION_NAME: $APPLICATION_NAME
                        DEPLOYMENT_GROUP: $DEPLOYMENT_GROUP
                        S3_BUCKET: $S3_BUCKET
                        DEPLOYMENT_CONFIG: $DEPLOYMENT_CONFIG
                        COMMAND: 'deploy'
                        WAIT: 'true'
                        VERSION_LABEL: 'my-app-1.0.0'
                        IGNORE_APPLICATION_STOP_FAILURES: 'true'
                        FILE_EXISTS_BEHAVIOR: 'OVERWRITE'

definitions: 
  services: 
    mysql: 
      image: mysql:latest
      command: --default-authentication-plugin=mysql_native_password
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: imobidb
      variables: 
        MYSQL_DATABASE: imobidb 
        MYSQL_ROOT_PASSWORD: root